OPENWEATHER_API_KEY = "83350e70e4de15a991533bdd03e028ab"
OPENAI_API_KEY="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"
